/* groovylint-disable-next-line CompileStatic */
pipeline {
    agent any

/*     triggers {
        pollSCM('H/5 * * * *') // Polls the SCM every 5 minutes
    }
 */
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/l07p/Jenkins.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                // Optionally install dependencies if any
                //sh 'pip install -r requirements.txt'
                echo 'Skipping dependency installation as no requirements are specified'
            }
        }

        stage('Run Python Tests') {
            steps {
                sh 'python3 -m unittest discover -s jobs/pipelines/arithmetic/tests'
            }
        }

        stage('Post Actions') {
            steps {
                echo 'Pipeline completed'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
